# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WqVtNxajka8Z1kzdNPX1SnR5-JMDLPEJ
"""

print("Olá!")